spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: "test"
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.globally_quoted_identifiers: true